# File to hold all excel formats

formats = {
    'header': {'bold': True, 'font_color': 'white',
                'font': 'Calibri', 'font_size': 12,
                'align': 'center', 'valign': 'top',
                'text_wrap': True, 
                'bg_color': '#7A869A',
                'border': True, 'border_color': '#cccccc'},
    'subheader': {'bold': True, 'font_color': 'black',
                    'font': 'Calibri', 'font_size': 12,
                    'align': 'center', 'valign': 'top',
                    'text_wrap': True, 
                    'bg_color': '#ffffff',
                    'border': True, 'border_color': '#cccccc'},
    'epic': {'bold': True, 'font_color': 'black',
            'font': 'Calibri', 'font_size': 12,
            'align': 'center', 'valign': 'top',
            'text_wrap': True,
            'bg_color': '#ffffff',
            'border': True, 'border_color': '#cccccc'},
    'SLNumDelta': {'align': 'center',
                    'valign': 'top',
                    'font_color': 'black',
                    'font': 'Calibri', 
                    'font_size': 11,
                    'bg_color': '#ffffff',
                    'border': True, 'border_color': '#cccccc'},
    'SLNum': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'bg_color': '#ffffff',
                'border': True, 'border_color': '#cccccc',
                'num_format': '#,##0'},
    'SLDec': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'bg_color': '#ffffff',
                'border': True, 'border_color': '#cccccc',
                'num_format': '#,##0.00'},
    'SLPer': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'border': True, 'border_color': '#cccccc',
                'bg_color': '#ffffff',
                'num_format': '0%'},
    'SLGreen': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'border': True, 'border_color': '#cccccc',
                'bg_color': '#57D9A3',
                'num_format': '0%'},
    'SLYellow': {'align': 'center',
                    'valign': 'top',
                    'font_color': 'black',
                    'font': 'Calibri', 
                    'font_size': 11,
                    'border': True, 'border_color': '#cccccc',
                    'bg_color': '#FFE380',
                    'num_format': '0%'},
    'SLRed': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'border': True, 'border_color': '#cccccc',
                'bg_color': '#DE350B',
                'num_format': '0%'},
    'SLBlue': {'align': 'center',
                'valign': 'top',
                'font_color': 'black',
                'font': 'Calibri', 
                'font_size': 11,
                'border': True, 'border_color': '#cccccc',
                'bg_color': '#2684FF',
                'num_format': '0%'},
    'title': {'font': 'Calibri', 
                'font_color': 'white',
                'font_size': 12, 
                'bold': True,
                'bg_color': '#003cb3',
                'align': 'center',
                'border': True,
                'border_color': 'black'},
    'redDelta': {'bg_color': '#FFC7CE',
                    'font_color': '#9C0006'},
    'slipStories': {'bg_color': '#cceeff'},
    'newStories': {'bg_color': '#ffffcc'}
}